version: '3'
services:
  fastapi_app:
    build:.
    ports:
      - "80:80"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
